language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t chrisneilson/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true chrisneilson/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-west-2-871595349623"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY